// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import Script from "next/script"
import "./globals.css"

// fontes extras usadas pela Lasy (mantém)
import "../lib/fonts"

// 👉 IMPORT DO BOTTOM NAV
import BottomNav from "@/components/ui/bottom-nav"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Divide Aí - Divida gastos com facilidade",
  description: "Organize e divida gastos entre amigos, casais e grupos",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>

      {/* pb-20 garante espaço para o bottom nav */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pb-20`}
      >
        {children}

        {/* NAVBAR GLOBAL – aparece em TODAS as telas */}
        <BottomNav />
      </body>
    </html>
  )
}
