// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import "../lib/fonts";

// ADICIONADO AGORA:
import ProtectedNavbar from "@/components/ProtectedNavbar";
import ActionModalProvider from "@/components/ActionModalProvider";
import { AuthProvider } from "@/context/AuthContext"; // 👈 AQUI

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Criado Pelo Brunola",
  description: "Projeto criado com Brunola",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#F7F7F7]`}
      >
        {/* 🔐 AUTH GLOBAL */}
      <AuthProvider>
  <ActionModalProvider>
    <div className="pb-32">{children}</div>

    {/* Navbar só aparece se estiver logado */}
    <ProtectedNavbar />
  </ActionModalProvider>
</AuthProvider>

